### ISSUE TITLE
StrongName / Signed Version

### ISSUE THREAD

**Issue by Angst003** [DIPSAS/Dapper.Oracle#21]
Hi,

Is it possible to have a signed assembly version of this library ? Dapper has a Dapper.StrongName.

**Comment by epaulsen** [comment]
Sorry for the late response, I somehow missed this issue.
As far as I can tell, Dapper it self isn't strongnamed.  This is metadata from the latest Dapper version downloaded from nuget.org:
![image](https://user-images.githubusercontent.com/2562403/55909429-4e885100-5bdc-11e9-938f-7b6b52d8ec4f.png)

When PublicKeyToken=null, you can pretty much assert that the assembly isn't strongly named.
And as long as Dapper itself don't have a strong name, we cannot strong name either.

**Comment by Angst003** [comment]
Hi, I know Dapper is not strongly named but Dapper.StrongName is...

`<?xml version="1.0" encoding="utf-8"?>
<coreProperties xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties">
  <dc:creator>Sam Saffron, Marc Gravell, Nick Craver</dc:creator>
  <dc:description>A high performance Micro-ORM supporting SQL Server, MySQL, Sqlite, SqlCE, Firebird etc..</dc:description>
  <dc:identifier>Dapper.StrongName</dc:identifier>
  <version>1.60.1</version>
  <keywords>orm sql micro-orm</keywords>
  <lastModifiedBy>NuGet.Build.Tasks.Pack, Version=4.9.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35;</lastModifiedBy>
</coreProperties>`

**Comment by epaulsen** [comment]
Ah, my misunderstanding, sorry.
That should be easy enough, just need to add another project file that generates a strong named assembly, and a new nuget package with the strong named assembly in it.

**Comment by epaulsen** [comment]
There is now a strong-named alternative:
[Dapper.Oracle.StrongName](https://www.nuget.org/packages/Dapper.Oracle.StrongName/1.2.0)
Exactly the same package, except it is strong-named, and depends upon Dapper.StrongName

Closing issue again.

**Comment by Angst003** [comment]
Great thank you very much.
