### ISSUE TITLE
OracleValueConverter.cs   (T)reflected   throw  System.InvalidCastException

### ISSUE THREAD

**Issue by yanghe1117** [DIPSAS/Dapper.Oracle#26]
![2019-05-08_224250](https://user-images.githubusercontent.com/12536366/57384404-22fc8480-71e3-11e9-9880-10c0f37daa5d.png)
`object reflected = valueProperty.GetValue(val);
                    return (T)reflected; `
//while T type is not the same as reflected, it throw System.InvalidCastException ,see the photo, decimal -->int 
                  
return (T)System.Convert.ChangeType(reflected, typeof(T)); //This is OK

**Comment by epaulsen** [comment]
Good catch.
I don't have time at the moment to fix this myself, please feel free to submit a pull-request, preferably with a unit-test that verifies the fix.

**Comment by epaulsen** [comment]
Fixed, will be released together with bulk sql feature later today
