### ISSUE TITLE
Set up build with Appveyor

### ISSUE THREAD

**Issue by andmos** [DIPSAS/Dapper.Oracle#3]
We need some CI and commits, so [Appveyor](https://www.appveyor.com/) is the best choice for Windows builds.

**Comment by andmos** [comment]
Need to install [psake](https://chocolatey.org/packages/psake) as part of the appveyor setup process. 
Seems like [that can be done quite easy](https://www.appveyor.com/blog/2014/11/06/appveyor-with-a-hint-of-chocolatey/).

**Comment by epaulsen** [comment]
**ahem**
Lines 11 through 14 here: [https://github.com/DIPSAS/Dapper.Oracle/blob/master/build.ps1](https://github.com/DIPSAS/Dapper.Oracle/blob/master/build.ps1)

**Comment by andmos** [comment]
Yeah, but it prompted me to be allowed to install the package. Will not work so well headless.
