### ISSUE TITLE
OracleDynamicParameters cannot be read before execution

### ISSUE THREAD

**Issue by opejanovic** [DIPSAS/Dapper.Oracle#36]
Hi,
first of all - great job. I have been using your libraries for a few weeks and it works very well!

I have noticed that it is not possible to get OracleDynamicParameters values before execution. 
Having logged DB procedure name and parameter value is extremely important for debugging.
Very often we have on production that DB procedure did not returned any value or exception and we need parameter value as an input to reproduce the issue.

I have a solution for this, and I will happily fix it if you allow me to. It is minor code change that you can easily review and approve. 

Regards
Ogi

**Comment by epaulsen** [comment]
Thanks for the feedback, glad that our oracle add-on works for you.
Any PR that adds value is appreciated, please submit a PR and we will review it shortly.
If you can add some unit-tests to verify that the new functionality works out that would be great.

**Comment by opejanovic** [comment]
@epaulsen I am unable to create a pull request because i have no permission to commit.

**Comment by epaulsen** [comment]
You cannot push directly to master, need to create PR in a branch created from master.
Follow scenario 2 here: https://yangsu.github.io/pull-request-tutorial/ 
Once a PR is reviewed and accepted I can merge it and create a new version.

**Comment by opejanovic** [comment]
@epaulsen thanks for the manual. I did exactly as it say but still i am getting error 403 - no permission
I have tried to create feature branch feature/read-parameters-before-execution
Please take a look at the log below:

`git pull origin master
From https://github.com/DIPSAS/Dapper.Oracle
 * branch            master     -> FETCH_HEAD
Already up to date.
git checkout -b feature/read-parameters-before-execution
Switched to a new branch 'feature/read-parameters-before-execution'
git push origin feature/read-parameters-before-execution
remote: Permission to DIPSAS/Dapper.Oracle.git denied to opejanovic.
fatal: unable to access 'https://github.com/DIPSAS/Dapper.Oracle.git/': The requested URL returned error: 403`

**Comment by opejanovic** [comment]
@epaulsen any ideas? I still have no access to the repository as you can see in comment above.

**Comment by epaulsen** [comment]
Not sure, I believe it has something to do with my company's org security settings for our github repos.  I have asked the admin guy to have a look at it, but that hasn't happenend yet, sorry.

You could try and to a PR from a fork instead? (click "fork" at the top of the repository front page)

**Comment by opejanovic** [comment]
@epaulsen i managed to create a PR from a fork. Please review the changes.
