### ISSUE TITLE
Oracle11g - OracleValueConverter - GetValue throws System.NullReferenceException

### ISSUE THREAD

**Issue by opejanovic** [DIPSAS/Dapper.Oracle#46]
Hi,
I got System.NullReferenceException while I was trying to read PLSQLAssociativeArray output parameter.

in line 63, we will have System.NullReferenceException if valueType.GetProperty("IsNull", typeof(bool)) is null
`var isNull = (bool)valueType.GetProperty("IsNull", typeof(bool))?.GetValue(value);`

I discovered this when I tried to get value from OracleString[]
This was working in previous version

![image](https://user-images.githubusercontent.com/16704836/97608376-8fd88f80-1a12-11eb-8fd9-ce75f8521697.png)

**Comment by opejanovic** [comment]
@Havagan you made this commit, can you fix it?

**Comment by opejanovic** [comment]
try running test:
`[Fact]
        public void GetOracleStringArray()
        {
            var oraString = new OracleString[] { "Foo", "Bar" };
            var result = OracleValueConverter.Convert<OracleString[]>(oraString);
            result.Should().HaveCount(2);
        }`

**Comment by opejanovic** [comment]
Pull request has been created

**Comment by epaulsen** [comment]
Shipped in version 2.0.1
https://www.nuget.org/packages/Dapper.Oracle/2.0.1

**Comment by opejanovic** [comment]
I think we can close this one. Thanks
