### ISSUE TITLE
Update to Net Core 3.1 or 5

### ISSUE THREAD

**Issue by KayakFisher205** [DIPSAS/Dapper.Oracle#51]
Would it be possible to Upgrade to Net 3.1 at the minimum or add 5.0 too? I didn't have any issues with it work so I don't expect too many code changes would be needed.

**Comment by epaulsen** [comment]
Dapper.Oracle is compiled for .Netstandard2.0, meaning that it works for .net >= 4.7 and .net core >= 2.0.

**Comment by KayakFisher205** [comment]
Under Visual Studio Preview 4, it didn't like it. I had no trouble with Preview 3. Locally, I created a net5.0 folder and copied the files from netstandard2.0 and it worked fine. I don't know if they introduced a bug from 3 to 4, or they are forcing to have all of the versions like they did for NetFramework.

I should have mentioned I was using the Preview version.

Thanks for looking into it.
